// <auto-generated />
namespace MessManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Expensetabledateattributedadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Expensetabledateattributedadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202009140846108_Expense table date attributed added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
